# Generated by Django 5.0.1 on 2024-02-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cinema', '0002_user_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='point',
            new_name='points',
        ),
    ]
